### ISSUE TITLE
Tol() takes no arguments

### ISSUE THREAD

**Issue by Katalien** [AndrosovAS/intvalpy#24]
I took code from the example here https://pypi.org/project/intvalpy/ .
Example:

import intvalpy as ip
A = ip.Interval([
  [[2, 4], [-2, 1]],
  [[-1, 2], [2, 4]]
])
b = ip.Interval([[-2, 2], [-2, 2]])
tol = ip.linear.Tol(A, b, maxQ=True)
print(tol)

When I try to run it I get an error: "TypeError: Tol() takes no arguments"
Can anyone tell me what is wrong and how to fix it?
Thanks

**Comment by AndrosovAS** [comment]
@Katalien 
Dear Katalien,
thank you very much for your feedback!

About a year ago I updated the function structure, but forgot to update the corresponding example in the README file.

Correct example: 

import intvalpy as ip
ip.precision.extendedPrecisionQ = False

A = ip.Interval([
  [[2, 4], [-2, 1]],
  [[-1, 2], [2, 4]]
])
b = ip.Interval([[-2, 2], [-2, 2]])

tol = ip.linear.Tol.maximize(
    A = A, 
    b = b,
    x0 = None,
    weight = None,
    linear_constraint = None
)
print(tol)

out: (array([0., 0.]), 2.0, 29, 53, 1)


You may be interested in articles on recognizing functions:
[1] https://www.mathnet.ru/links/b674f826918eb4b9fe4ce5aa1b737c16/vyurm326.pdf (ru)
[2] https://www.researchgate.net/publication/324182397_Weak_and_Strong_Compatibility_in_Data_Fitting_Problems_under_Interval_Uncertainty (en)
[3] http://www.ict.nsc.ru/jct/getfile.php?id=1551 (ru)

If you have any more questions about interval calculations or the IntvalPy library, I am always at your service.

P.S.
Если Ваш родной язык русский, то предлагаю общаться на нём :)

**Comment by Katalien** [comment]
Спасибо большое за ответ!
Да, родной язык - русский :)

**Comment by AndrosovAS** [comment]
Отлично!
